---
- hosts: website
  tasks:
    # Installation tasks
    # ##################
    - name: Enable copr
      ansible.builtin.dnf:
        name: "dnf-command(copr)"
        state: present
    - name: Enable caddy copr
      community.general.copr:
        name: "@caddy/caddy"
        state: enabled

    - name: Install server maintenance
      ansible.builtin.dnf:
        name: "fail2ban"
        state: present

    - name: Install web server requirements
      ansible.builtin.dnf:
        name:
          - caddy
          - git
          - mailcap
          - python3-aiohttp
        state: present

    - name: Install server monitoring tools
      ansible.builtin.dnf:
        name:
          - golang-github-prometheus
          - golang-github-prometheus-alertmanager
          - golang-github-prometheus-node-exporter
          - grafana
          # Remove this when Loki is packaged.
          - podman
        state: present

    # Caddy server setup
    # ##################
    - name: Configure Caddy
      ansible.builtin.copy:
        src: "{{playbook_dir}}/caddy/Caddyfile"
        dest: /etc/caddy/Caddyfile
      notify: Reload Caddy

    - name: Configure Caddy system service
      ansible.builtin.file:
        path: /etc/systemd/system/caddy.service.d
        state: directory
        mode: 0755
    - name: Configure Caddy system service
      ansible.builtin.copy:
        src: "{{playbook_dir}}/caddy/caddy.service.override"
        dest: /etc/systemd/system/caddy.service.d/override.conf
      notify:
        - Reload systemd
        - Restart Caddy

    - name: Enable Caddy service
      ansible.builtin.systemd:
        name: caddy.service
        enabled: true
        state: started

  # Handlers restart/reload services at playbook completion
  # #######################################################
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Reload Caddy
      ansible.builtin.systemd:
        name: caddy
        state: reloaded

    - name: Restart Caddy
      ansible.builtin.systemd:
        name: caddy
        state: restarted
