---
- hosts: website
  tasks:
    - name: Enable copr
      ansible.builtin.dnf:
        name: "dnf-command(copr)"
        state: present
    - name: Enable caddy copr
      community.general.copr:
        name: "@caddy/caddy"
        state: enabled

    - name: Install server maintenance
      ansible.builtin.dnf:
        name: "fail2ban"
        state: present

    - name: Install web server requirements
      ansible.builtin.dnf:
        name:
          - caddy
          - git
          - mailcap
          - python3-aiohttp
        state: present

    - name: Install server monitoring tools
      ansible.builtin.dnf:
        name:
          - golang-github-prometheus
          - golang-github-prometheus-alertmanager
          - golang-github-prometheus-node-exporter
          - grafana
          # Remove this when Loki is packaged.
          - podman
        state: present
