---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Browser uses Grafana to access Prometheus so it doesn't need to be public.
    access: proxy
    url: http://localhost:9090
    isDefault: true
    version: 1
    editable: false
